// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfcz6Y71aC6C4TAi4QIgJJ0q637edVP1k',
    appId: '1:237058241475:web:2e4a3516659f7176558376',
    messagingSenderId: '237058241475',
    projectId: 'grocery-app-4e8b9',
    authDomain: 'grocery-app-4e8b9.firebaseapp.com',
    storageBucket: 'grocery-app-4e8b9.firebasestorage.app',
    measurementId: 'G-ZBJ0PCR9LQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfcz6Y71aC6C4TAi4QIgJJ0q637edVP1k',
    appId: '1:237058241475:android:2e4a3516659f7176558376',
    messagingSenderId: '237058241475',
    projectId: 'grocery-app-4e8b9',
    storageBucket: 'grocery-app-4e8b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfcz6Y71aC6C4TAi4QIgJJ0q637edVP1k',
    appId: '1:237058241475:ios:2e4a3516659f7176558376',
    messagingSenderId: '237058241475',
    projectId: 'grocery-app-4e8b9',
    storageBucket: 'grocery-app-4e8b9.firebasestorage.app',
    iosBundleId: 'com.example.grocery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfcz6Y71aC6C4TAi4QIgJJ0q637edVP1k',
    appId: '1:237058241475:macos:2e4a3516659f7176558376',
    messagingSenderId: '237058241475',
    projectId: 'grocery-app-4e8b9',
    storageBucket: 'grocery-app-4e8b9.firebasestorage.app',
    iosBundleId: 'com.example.grocery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfcz6Y71aC6C4TAi4QIgJJ0q637edVP1k',
    appId: '1:237058241475:windows:2e4a3516659f7176558376',
    messagingSenderId: '237058241475',
    projectId: 'grocery-app-4e8b9',
    storageBucket: 'grocery-app-4e8b9.firebasestorage.app',
  );
}
